### ISSUE TITLE
The version used by the dependent library HEALPix in the SID library 

### ISSUE THREAD

**Issue by yuancf1024** [lnicastro/SID#1]
Dear Professor Luciano Nicastro, Hello! Thank you for your contributions to the field of astronomy in the open source software community - the development of the spherical index of relational databases "SID", the implementation of a powerful astronomical directory index system and the spherical coordinates of other data, stored in the MySQL/MariaDB database.
I am a programmer in the field of database development, and recently I worked on an astronomical data processing project, which also tried to add the spherical index feature of astronomical data to the database. In your project, you rely on the tripartite library [HEALPix](https://healpix.sourceforge.io/downloads.php).
So far, the HEALPix library has been updated to v3.82, and based on the code files and commit history in your project, I'm guessing that you're using the [Healpix_3.31 version](https://sourceforge.net/projects/healpix/files/Healpix_3.31/), but since you didn't detail it in the README, I'm not quite sure about the exact version.
Due to the issue of library version update, I would like to know the specific version of the HEALPix library that you rely on in your project, and hope that you can let me know when you have time. Thank you for your reading and looking forward to your reply!
Best wishes!
Chris

**Comment by lnicastro** [comment]
Chris, I confirm it is version 3.31, as it is for [DIF](https://github.com/lnicastro/DIF). Still it should make no difference with respect the latest version. I will eventually test it and update the source code.

**Comment by yuancf1024** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yuancf1024** [comment]
Thank you for your prompt reply! In our current work, we need to make some minor changes to the HEALPix library, so we are more concerned about the specific version we use.
Best Regards!

**Comment by yuancf1024** [comment]
> Chris, I confirm it is version 3.31, as it is for [DIF](https://github.com/lnicastro/DIF). Still it should make no difference with respect the latest version. I will eventually test it and update the source code.

Thank you for your prompt reply! In our current work, we need to make some minor changes to the HEALPix library, so we are more concerned about the specific version we use.
Best Regards!
